# Generated by Django 5.2.3 on 2025-06-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
    ]
