# Generated by Django 5.2.3 on 2025-07-07 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_message_options_alter_topic_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='agent_response',
        ),
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
